sudo: false

language: node_js
os:
  - linux
  - osx
node_js:
  - "node"
  - "12"

install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi
script:
  - |
    echo ">>> Compile vscode-test"
    npm ci && npm run vscode:prepublish
    echo ">>> Compiled vscode-test"
    echo ">>> Run integration tests"
    npm test
