sudo: false

language: node_js
os:
  - linux
  - osx
node_js:
  - "node"
  - "12"

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi

script:
  - npm test
  # - npm run vscode:prepublish
